/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class __IB {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected __IB(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__IB obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete___IB(swigCPtr);
    }
    swigCPtr = 0;
  }

  public int GetFreeMemory() {
    return IBJNI.__IB_GetFreeMemory(swigCPtr, this);
  }

  public int GetTotalMemory() {
    return IBJNI.__IB_GetTotalMemory(swigCPtr, this);
  }

  public int Hostid() {
    return IBJNI.__IB_Hostid(swigCPtr, this);
  }

  public int SerialID() {
    return IBJNI.__IB_SerialID(swigCPtr, this);
  }

  public boolean FileGlob(String pattern, String str) {
    return IBJNI.__IB_FileGlob(swigCPtr, this, pattern, str);
  }

  public boolean Glob(String pattern, String str, boolean dot_special) {
    return IBJNI.__IB_Glob__SWIG_0(swigCPtr, this, pattern, str, dot_special);
  }

  public boolean Glob(String pattern, String str) {
    return IBJNI.__IB_Glob__SWIG_1(swigCPtr, this, pattern, str);
  }

  public String GetUserHome(String user) {
    return IBJNI.__IB_GetUserHome(swigCPtr, this, user);
  }

  public boolean DirectoryExists(String Path) {
    return IBJNI.__IB_DirectoryExists(swigCPtr, this, Path);
  }

  public boolean FileExists(String Path) {
    return IBJNI.__IB_FileExists(swigCPtr, this, Path);
  }

  public boolean ExeExists(String Path) {
    return IBJNI.__IB_ExeExists(swigCPtr, this, Path);
  }

  public int FileLink(String Source, String Dest) {
    return IBJNI.__IB_FileLink(swigCPtr, this, Source, Dest);
  }

  public void SendDebugMessage(String msg) {
    IBJNI.__IB_SendDebugMessage(swigCPtr, this, msg);
  }

  public void SendInfoMessage(String msg) {
    IBJNI.__IB_SendInfoMessage(swigCPtr, this, msg);
  }

  public void SendNoticeMessage(String msg) {
    IBJNI.__IB_SendNoticeMessage(swigCPtr, this, msg);
  }

  public void SendWarningMessage(String msg) {
    IBJNI.__IB_SendWarningMessage(swigCPtr, this, msg);
  }

  public void SendErrorMessage(String msg) {
    IBJNI.__IB_SendErrorMessage(swigCPtr, this, msg);
  }

  public void SendErrnoMessage(String msg) {
    IBJNI.__IB_SendErrnoMessage(swigCPtr, this, msg);
  }

  public void SendFatalMessage(String msg) {
    IBJNI.__IB_SendFatalMessage(swigCPtr, this, msg);
  }

  public void SendPanicMessage(String msg) {
    IBJNI.__IB_SendPanicMessage(swigCPtr, this, msg);
  }

  public __IB() {
    this(IBJNI.new___IB(), true);
  }

}
