/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CHARSET {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CHARSET(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CHARSET obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_CHARSET(swigCPtr);
    }
    swigCPtr = 0;
  }

  public CHARSET(String Name) {
    this(IBJNI.new_CHARSET(Name), true);
  }

  public boolean Ok() {
    return IBJNI.CHARSET_Ok(swigCPtr, this);
  }

  public String Name() {
    return IBJNI.CHARSET_Name(swigCPtr, this);
  }

  public String HtmlCat(String Input, boolean Anchor) {
    return IBJNI.CHARSET_HtmlCat__SWIG_0(swigCPtr, this, Input, Anchor);
  }

  public String HtmlCat(String Input) {
    return IBJNI.CHARSET_HtmlCat__SWIG_1(swigCPtr, this, Input);
  }

  public String ToLower(String String) {
    return IBJNI.CHARSET_ToLower(swigCPtr, this, String);
  }

  public String ToUpper(String String) {
    return IBJNI.CHARSET_ToUpper(swigCPtr, this, String);
  }

  public int ib_isalpha(char c) {
    return IBJNI.CHARSET_ib_isalpha(swigCPtr, this, c);
  }

  public int ib_isupper(char c) {
    return IBJNI.CHARSET_ib_isupper(swigCPtr, this, c);
  }

  public int ib_islower(char c) {
    return IBJNI.CHARSET_ib_islower(swigCPtr, this, c);
  }

  public int ib_isdigit(char c) {
    return IBJNI.CHARSET_ib_isdigit(swigCPtr, this, c);
  }

  public int ib_isxdigit(char c) {
    return IBJNI.CHARSET_ib_isxdigit(swigCPtr, this, c);
  }

  public int ib_isalnum(char c) {
    return IBJNI.CHARSET_ib_isalnum(swigCPtr, this, c);
  }

  public int ib_isspace(char c) {
    return IBJNI.CHARSET_ib_isspace(swigCPtr, this, c);
  }

  public int ib_ispunct(char c) {
    return IBJNI.CHARSET_ib_ispunct(swigCPtr, this, c);
  }

  public int ib_isprint(char c) {
    return IBJNI.CHARSET_ib_isprint(swigCPtr, this, c);
  }

  public int ib_isgraph(char c) {
    return IBJNI.CHARSET_ib_isgraph(swigCPtr, this, c);
  }

  public int ib_iscntrl(char c) {
    return IBJNI.CHARSET_ib_iscntrl(swigCPtr, this, c);
  }

  public int ib_iswhite(char c) {
    return IBJNI.CHARSET_ib_iswhite(swigCPtr, this, c);
  }

  public int ib_isascii(char c) {
    return IBJNI.CHARSET_ib_isascii(swigCPtr, this, c);
  }

  public int ib_islatin1(char c) {
    return IBJNI.CHARSET_ib_islatin1(swigCPtr, this, c);
  }

  public int ib_toupper(char c) {
    return IBJNI.CHARSET_ib_toupper(swigCPtr, this, c);
  }

  public int ib_tolower(char c) {
    return IBJNI.CHARSET_ib_tolower(swigCPtr, this, c);
  }

  public int ib_toascii(char c) {
    return IBJNI.CHARSET_ib_toascii(swigCPtr, this, c);
  }

  public int isTermChr(char c) {
    return IBJNI.CHARSET_isTermChr(swigCPtr, this, c);
  }

  public int isWordSep(char c) {
    return IBJNI.CHARSET_isWordSep(swigCPtr, this, c);
  }

  public int isTermWhite(char c) {
    return IBJNI.CHARSET_isTermWhite(swigCPtr, this, c);
  }

  public int UCS(char Ch) {
    return IBJNI.CHARSET_UCS(swigCPtr, this, Ch);
  }

}
