/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DATERANGE {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DATERANGE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DATERANGE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_DATERANGE(swigCPtr);
    }
    swigCPtr = 0;
  }

  public DATERANGE(SRCH_DATE Start, SRCH_DATE End) {
    this(IBJNI.new_DATERANGE(SRCH_DATE.getCPtr(Start), Start, SRCH_DATE.getCPtr(End), End), true);
  }

  public SRCH_DATE GetStart() {
    return new SRCH_DATE(IBJNI.DATERANGE_GetStart(swigCPtr, this), true);
  }

  public SRCH_DATE GetEnd() {
    return new SRCH_DATE(IBJNI.DATERANGE_GetEnd(swigCPtr, this), true);
  }

  public void SetStart(SRCH_DATE NewStart) {
    IBJNI.DATERANGE_SetStart(swigCPtr, this, SRCH_DATE.getCPtr(NewStart), NewStart);
  }

  public void SetEnd(SRCH_DATE NewEnd) {
    IBJNI.DATERANGE_SetEnd(swigCPtr, this, SRCH_DATE.getCPtr(NewEnd), NewEnd);
  }

  public boolean Ok() {
    return IBJNI.DATERANGE_Ok(swigCPtr, this);
  }

  public boolean Defined() {
    return IBJNI.DATERANGE_Defined(swigCPtr, this);
  }

  public boolean Contains(SRCH_DATE TestDate) {
    return IBJNI.DATERANGE_Contains(swigCPtr, this, SRCH_DATE.getCPtr(TestDate), TestDate);
  }

  public String ISO() {
    return IBJNI.DATERANGE_ISO(swigCPtr, this);
  }

  public String RFC() {
    return IBJNI.DATERANGE_RFC(swigCPtr, this);
  }

  public String Strftime(String fmt, String sep) {
    return IBJNI.DATERANGE_Strftime__SWIG_0(swigCPtr, this, fmt, sep);
  }

  public String Strftime(String fmt) {
    return IBJNI.DATERANGE_Strftime__SWIG_1(swigCPtr, this, fmt);
  }

  public double Duration() {
    return IBJNI.DATERANGE_Duration(swigCPtr, this);
  }

}
