/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DOC_ID {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DOC_ID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DOC_ID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_DOC_ID(swigCPtr);
    }
    swigCPtr = 0;
  }

  public DOC_ID(String GlobalKey) {
    this(IBJNI.new_DOC_ID(GlobalKey), true);
  }

  public boolean Equals(DOC_ID OtherDoc) {
    return IBJNI.DOC_ID_Equals(swigCPtr, this, DOC_ID.getCPtr(OtherDoc), OtherDoc);
  }

  public int Compare(DOC_ID OtherDoc) {
    return IBJNI.DOC_ID_Compare(swigCPtr, this, DOC_ID.getCPtr(OtherDoc), OtherDoc);
  }

  public String GlobalKey() {
    return IBJNI.DOC_ID_GlobalKey(swigCPtr, this);
  }

}
