/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DOCTYPE_ID {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DOCTYPE_ID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DOCTYPE_ID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_DOCTYPE_ID(swigCPtr);
    }
    swigCPtr = 0;
  }

  public DOCTYPE_ID(String DocType) {
    this(IBJNI.new_DOCTYPE_ID(DocType), true);
  }

  public String DocumentType() {
    return IBJNI.DOCTYPE_ID_DocumentType(swigCPtr, this);
  }

  public void Set(String Value) {
    IBJNI.DOCTYPE_ID_Set(swigCPtr, this, Value);
  }

  public String Get() {
    return IBJNI.DOCTYPE_ID_Get(swigCPtr, this);
  }

  public String c_str() {
    return IBJNI.DOCTYPE_ID_c_str(swigCPtr, this);
  }

  public boolean IsDefined() {
    return IBJNI.DOCTYPE_ID_IsDefined(swigCPtr, this);
  }

  public boolean Equals(DOCTYPE_ID Other) {
    return IBJNI.DOCTYPE_ID_Equals(swigCPtr, this, DOCTYPE_ID.getCPtr(Other), Other);
  }

}
