/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DOCTYPE {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DOCTYPE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DOCTYPE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_DOCTYPE(swigCPtr);
    }
    swigCPtr = 0;
  }

  public DOCTYPE() {
    this(IBJNI.new_DOCTYPE__SWIG_0(), true);
  }

  public DOCTYPE(IDBOBJ DbParent, String NewDoctype) {
    this(IBJNI.new_DOCTYPE__SWIG_1(IDBOBJ.getCPtr(DbParent), DbParent, NewDoctype), true);
  }

  public DOCTYPE(IDBOBJ DbParent) {
    this(IBJNI.new_DOCTYPE__SWIG_2(IDBOBJ.getCPtr(DbParent), DbParent), true);
  }

  public SRCH_DATE ParseDate(String Buffer, String FieldName) {
    return new SRCH_DATE(IBJNI.DOCTYPE_ParseDate(swigCPtr, this, Buffer, FieldName), true);
  }

  public DATERANGE ParseDateRange(String Buffer, String FieldName) {
    return new DATERANGE(IBJNI.DOCTYPE_ParseDateRange(swigCPtr, this, Buffer, FieldName), true);
  }

}
