/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DTREG {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DTREG(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DTREG obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_DTREG(swigCPtr);
    }
    swigCPtr = 0;
  }

  public DTREG(IDBOBJ DbParent) {
    this(IBJNI.new_DTREG__SWIG_0(IDBOBJ.getCPtr(DbParent), DbParent), true);
  }

  public DTREG(IDBOBJ DbParent, String PluginsPath) {
    this(IBJNI.new_DTREG__SWIG_1(IDBOBJ.getCPtr(DbParent), DbParent, PluginsPath), true);
  }

  public boolean PluginExists(String Name) {
    return IBJNI.DTREG_PluginExists(swigCPtr, this, Name);
  }

  public void AddPluginPath(String Path) {
    IBJNI.DTREG_AddPluginPath(swigCPtr, this, Path);
  }

  public DOCTYPE GetDocTypePtr(String Doctype) {
    long cPtr = IBJNI.DTREG_GetDocTypePtr__SWIG_0(swigCPtr, this, Doctype);
    return (cPtr == 0) ? null : new DOCTYPE(cPtr, false);
  }

  public DOCTYPE GetDocTypePtr(DOCTYPE_ID Id) {
    long cPtr = IBJNI.DTREG_GetDocTypePtr__SWIG_1(swigCPtr, this, DOCTYPE_ID.getCPtr(Id), Id);
    return (cPtr == 0) ? null : new DOCTYPE(cPtr, false);
  }

  public DOCTYPE GetDocTypePtr(String DocType, String DocTypeID) {
    long cPtr = IBJNI.DTREG_GetDocTypePtr__SWIG_2(swigCPtr, this, DocType, DocTypeID);
    return (cPtr == 0) ? null : new DOCTYPE(cPtr, false);
  }

  public boolean ValidateDocType(String DocType) {
    return IBJNI.DTREG_ValidateDocType__SWIG_0(swigCPtr, this, DocType);
  }

  public boolean ValidateDocType(DOCTYPE_ID Id) {
    return IBJNI.DTREG_ValidateDocType__SWIG_1(swigCPtr, this, DOCTYPE_ID.getCPtr(Id), Id);
  }

  public STRLIST GetDocTypeList() {
    return new STRLIST(IBJNI.DTREG_GetDocTypeList(swigCPtr, this), false);
  }

  public int Version() {
    return IBJNI.DTREG_Version(swigCPtr, this);
  }

}
