/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FC {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FC(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FC obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_FC(swigCPtr);
    }
    swigCPtr = 0;
  }

  public FC(FC Fc) {
    this(IBJNI.new_FC__SWIG_0(FC.getCPtr(Fc), Fc), true);
  }

  public FC(SWIGTYPE_p_unsigned_long_long GpPair) {
    this(IBJNI.new_FC__SWIG_1(SWIGTYPE_p_unsigned_long_long.getCPtr(GpPair)), true);
  }

  public FC(java.math.BigInteger Start, java.math.BigInteger End) {
    this(IBJNI.new_FC__SWIG_2(Start, End), true);
  }

  public FC(long Start, long End) {
    this(IBJNI.new_FC__SWIG_3(Start, End), true);
  }

  public FC(long Start) {
    this(IBJNI.new_FC__SWIG_4(Start), true);
  }

  public FC() {
    this(IBJNI.new_FC__SWIG_5(), true);
  }

  public void SetFieldStart(long NewFieldStart) {
    IBJNI.FC_SetFieldStart(swigCPtr, this, NewFieldStart);
  }

  public void SetFieldEnd(long NewFieldEnd) {
    IBJNI.FC_SetFieldEnd(swigCPtr, this, NewFieldEnd);
  }

  public long GetFieldStart() {
    return IBJNI.FC_GetFieldStart(swigCPtr, this);
  }

  public long GetFieldEnd() {
    return IBJNI.FC_GetFieldEnd(swigCPtr, this);
  }

  public long GetLength() {
    return IBJNI.FC_GetLength(swigCPtr, this);
  }

  public int Compare(FC Fc) {
    return IBJNI.FC_Compare(swigCPtr, this, FC.getCPtr(Fc), Fc);
  }

  public int Contains(FC Fc) {
    return IBJNI.FC_Contains(swigCPtr, this, FC.getCPtr(Fc), Fc);
  }

  public void FlipBytes() {
    IBJNI.FC_FlipBytes(swigCPtr, this);
  }

}
