/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FCACHE {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FCACHE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FCACHE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_FCACHE(swigCPtr);
    }
    swigCPtr = 0;
  }

  public FCACHE(IDBOBJ parent) {
    this(IBJNI.new_FCACHE(IDBOBJ.getCPtr(parent), parent), true);
  }

  public boolean Ok() {
    return IBJNI.FCACHE_Ok(swigCPtr, this);
  }

  public boolean ValidateInField(java.math.BigInteger HitGp) {
    return IBJNI.FCACHE_ValidateInField__SWIG_0(swigCPtr, this, HitGp);
  }

  public boolean ValidateInField(FC HitGp) {
    return IBJNI.FCACHE_ValidateInField__SWIG_1(swigCPtr, this, FC.getCPtr(HitGp), HitGp);
  }

  public boolean ValidateInField(java.math.BigInteger HitGp, String FieldName) {
    return IBJNI.FCACHE_ValidateInField__SWIG_2(swigCPtr, this, HitGp, FieldName);
  }

  public boolean ValidateInField(FC HitFc, String FieldName) {
    return IBJNI.FCACHE_ValidateInField__SWIG_3(swigCPtr, this, FC.getCPtr(HitFc), HitFc, FieldName);
  }

  public long GetTotal() {
    return IBJNI.FCACHE_GetTotal(swigCPtr, this);
  }

  public boolean SetFieldName(String fieldName, boolean Disk) {
    return IBJNI.FCACHE_SetFieldName__SWIG_0(swigCPtr, this, fieldName, Disk);
  }

  public boolean SetFieldName(String fieldName) {
    return IBJNI.FCACHE_SetFieldName__SWIG_1(swigCPtr, this, fieldName);
  }

  public String GetFieldName() {
    return IBJNI.FCACHE_GetFieldName(swigCPtr, this);
  }

}
