/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IB implements IBConstants {
  public static int getDbStateInvalid() {
    return IBJNI.DbStateInvalid_get();
  }

  public static int getDbStateReady() {
    return IBJNI.DbStateReady_get();
  }

  public static int getDbStateBusy() {
    return IBJNI.DbStateBusy_get();
  }

  public static String ResolveConfigPath(String Filename) {
    return IBJNI.ResolveConfigPath(Filename);
  }

  public static String ResolveBinPath(String filename) {
    return IBJNI.ResolveBinPath(filename);
  }

  public static String ExpandFileSpec(String FileSpec) {
    return IBJNI.ExpandFileSpec(FileSpec);
  }

  public static boolean set_syslog(String device) {
    return IBJNI.set_syslog(device);
  }

  public static boolean log_init(int level, String prefix, String name) {
    return IBJNI.log_init__SWIG_0(level, prefix, name);
  }

  public static boolean log_init(int level, String prefix) {
    return IBJNI.log_init__SWIG_1(level, prefix);
  }

  public static boolean log_init(int level) {
    return IBJNI.log_init__SWIG_2(level);
  }

  public static void log_message(int level, String string) {
    IBJNI.log_message(level, string);
  }

}
