/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface IBConstants {
  public final static int GDT_FALSE = IBJNI.GDT_FALSE_get();
  public final static int GDT_TRUE = IBJNI.GDT_TRUE_get();
  public final static String ELEMENT_Full = IBJNI.ELEMENT_Full_get();
  public final static String ELEMENT_Brief = IBJNI.ELEMENT_Brief_get();
  public final static String ELEMENT_Short = IBJNI.ELEMENT_Short_get();
  public final static String ELEMENT_G = IBJNI.ELEMENT_G_get();
  public final static String ELEMENT_Raw = IBJNI.ELEMENT_Raw_get();
  public final static String ELEMENT_Location = IBJNI.ELEMENT_Location_get();
  public final static String ELEMENT_Metadata = IBJNI.ELEMENT_Metadata_get();
  public final static String RECORDSYNTAX_Sutrs = IBJNI.RECORDSYNTAX_Sutrs_get();
  public final static String RECORDSYNTAX_Usmarc = IBJNI.RECORDSYNTAX_Usmarc_get();
  public final static String RECORDSYNTAX_Html = IBJNI.RECORDSYNTAX_Html_get();
  public final static String RECORDSYNTAX_Sgml = IBJNI.RECORDSYNTAX_Sgml_get();
  public final static String RECORDSYNTAX_Xml = IBJNI.RECORDSYNTAX_Xml_get();
  public final static String RECORDSYNTAX_Raw = IBJNI.RECORDSYNTAX_Raw_get();
  public final static String RECORDSYNTAX_DVBHtml = IBJNI.RECORDSYNTAX_DVBHtml_get();
  public final static String copyright = IBJNI.copyright_get();
  public final static String version = IBJNI.version_get();
  public final static int LOG_PANIC = IBJNI.LOG_PANIC_get();
  public final static int LOG_FATAL = IBJNI.LOG_FATAL_get();
  public final static int LOG_ERROR = IBJNI.LOG_ERROR_get();
  public final static int LOG_ERRNO = IBJNI.LOG_ERRNO_get();
  public final static int LOG_WARN = IBJNI.LOG_WARN_get();
  public final static int LOG_NOTICE = IBJNI.LOG_NOTICE_get();
  public final static int LOG_INFO = IBJNI.LOG_INFO_get();
  public final static int LOG_DEBUG = IBJNI.LOG_DEBUG_get();
  public final static int LOG_ALL = IBJNI.LOG_ALL_get();
  public final static String DEVICE_STDERR = IBJNI.DEVICE_STDERR_get();
  public final static String DEVICE_STDOUT = IBJNI.DEVICE_STDOUT_get();
  public final static String DEVICE_SYSLOG = IBJNI.DEVICE_SYSLOG_get();
  public final static String DEVICE_LOCAL0 = IBJNI.DEVICE_LOCAL0_get();
  public final static String DEVICE_LOCAL1 = IBJNI.DEVICE_LOCAL1_get();
  public final static String DEVICE_LOCAL2 = IBJNI.DEVICE_LOCAL2_get();
  public final static String DEVICE_LOCAL3 = IBJNI.DEVICE_LOCAL3_get();
  public final static String DEVICE_LOCAL4 = IBJNI.DEVICE_LOCAL4_get();
  public final static String DEVICE_LOCAL5 = IBJNI.DEVICE_LOCAL5_get();
  public final static String DEVICE_LOCAL6 = IBJNI.DEVICE_LOCAL6_get();
  public final static String DEVICE_LOCAL7 = IBJNI.DEVICE_LOCAL7_get();
}
