/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IDB_STATS {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IDB_STATS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IDB_STATS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_IDB_STATS(swigCPtr);
    }
    swigCPtr = 0;
  }

  public IDB_STATS() {
    this(IBJNI.new_IDB_STATS(), true);
  }

  public void SetHits(long nHits) {
    IBJNI.IDB_STATS_SetHits(swigCPtr, this, nHits);
  }

  public void SetTotal(long nTotal) {
    IBJNI.IDB_STATS_SetTotal(swigCPtr, this, nTotal);
  }

  public long GetTotal() {
    return IBJNI.IDB_STATS_GetTotal(swigCPtr, this);
  }

  public long GetHits() {
    return IBJNI.IDB_STATS_GetHits(swigCPtr, this);
  }

  public void Clear() {
    IBJNI.IDB_STATS_Clear(swigCPtr, this);
  }

  public void SetName(String newName) {
    IBJNI.IDB_STATS_SetName(swigCPtr, this, newName);
  }

  public String GetName() {
    return IBJNI.IDB_STATS_GetName(swigCPtr, this);
  }

}
