/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IDBOBJ {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IDBOBJ(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IDBOBJ obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_IDBOBJ(swigCPtr);
    }
    swigCPtr = 0;
  }

  public IDBOBJ() {
    this(IBJNI.new_IDBOBJ(), true);
  }

  public boolean getUseRelativePaths() {
    return IBJNI.IDBOBJ_getUseRelativePaths(swigCPtr, this);
  }

  public boolean setUseRelativePaths(boolean val) {
    return IBJNI.IDBOBJ_setUseRelativePaths__SWIG_0(swigCPtr, this, val);
  }

  public boolean setUseRelativePaths() {
    return IBJNI.IDBOBJ_setUseRelativePaths__SWIG_1(swigCPtr, this);
  }

  public String RelativizePathname(String Path) {
    return IBJNI.IDBOBJ_RelativizePathname(swigCPtr, this, Path);
  }

  public String ResolvePathname(String Path) {
    return IBJNI.IDBOBJ_ResolvePathname(swigCPtr, this, Path);
  }

}
