/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class INDEX_ID {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected INDEX_ID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(INDEX_ID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_INDEX_ID(swigCPtr);
    }
    swigCPtr = 0;
  }

  public INDEX_ID() {
    this(IBJNI.new_INDEX_ID__SWIG_0(), true);
  }

  public INDEX_ID(INDEX_ID Other) {
    this(IBJNI.new_INDEX_ID__SWIG_1(INDEX_ID.getCPtr(Other), Other), true);
  }

  public int GetIndex() {
    return IBJNI.INDEX_ID_GetIndex(swigCPtr, this);
  }

  public void SetIndex(int index) {
    IBJNI.INDEX_ID_SetIndex(swigCPtr, this, index);
  }

  public void SetMdtIndex(long NewMdtIndex) {
    IBJNI.INDEX_ID_SetMdtIndex(swigCPtr, this, NewMdtIndex);
  }

  public long GetMdtIndex() {
    return IBJNI.INDEX_ID_GetMdtIndex(swigCPtr, this);
  }

  public void SetVirtualIndex(int NewvIndex) {
    IBJNI.INDEX_ID_SetVirtualIndex(swigCPtr, this, NewvIndex);
  }

  public int GetVirtualIndex() {
    return IBJNI.INDEX_ID_GetVirtualIndex(swigCPtr, this);
  }

  public boolean Equals(INDEX_ID Val) {
    return IBJNI.INDEX_ID_Equals(swigCPtr, this, INDEX_ID.getCPtr(Val), Val);
  }

  public int Compare(INDEX_ID Val) {
    return IBJNI.INDEX_ID_Compare(swigCPtr, this, INDEX_ID.getCPtr(Val), Val);
  }

}
