/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IRSET {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IRSET(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IRSET obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_IRSET(swigCPtr);
    }
    swigCPtr = 0;
  }

  public IRSET(IDBOBJ IdbPtr, long Reserve) {
    this(IBJNI.new_IRSET__SWIG_0(IDBOBJ.getCPtr(IdbPtr), IdbPtr, Reserve), true);
  }

  public IRSET(IDBOBJ IdbPtr) {
    this(IBJNI.new_IRSET__SWIG_1(IDBOBJ.getCPtr(IdbPtr), IdbPtr), true);
  }

  public IRSET getself() {
    return new IRSET(IBJNI.IRSET_getself(swigCPtr, this), false);
  }

  public void Write(String Path) {
    IBJNI.IRSET_Write(swigCPtr, this, Path);
  }

  public void Read(String Path) {
    IBJNI.IRSET_Read(swigCPtr, this, Path);
  }

  public void LoadTable(String FileName) {
    IBJNI.IRSET_LoadTable(swigCPtr, this, FileName);
  }

  public void SaveTable(String FileName) {
    IBJNI.IRSET_SaveTable(swigCPtr, this, FileName);
  }

  public boolean SaveSearch(String FileName, QUERY Query) {
    return IBJNI.IRSET_SaveSearch(swigCPtr, this, FileName, QUERY.getCPtr(Query), Query);
  }

  public QUERY LoadSearch(String FileName) {
    long cPtr = IBJNI.IRSET_LoadSearch(swigCPtr, this, FileName);
    return (cPtr == 0) ? null : new QUERY(cPtr, false);
  }

  public RSET GetRset(long Total) {
    long cPtr = IBJNI.IRSET_GetRset__SWIG_0(swigCPtr, this, Total);
    return (cPtr == 0) ? null : new RSET(cPtr, true);
  }

  public RSET GetRset() {
    long cPtr = IBJNI.IRSET_GetRset__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new RSET(cPtr, true);
  }

  public RSET Fill(long Start, long End) {
    long cPtr = IBJNI.IRSET_Fill__SWIG_0(swigCPtr, this, Start, End);
    return (cPtr == 0) ? null : new RSET(cPtr, true);
  }

  public RSET Fill(long Start) {
    long cPtr = IBJNI.IRSET_Fill__SWIG_1(swigCPtr, this, Start);
    return (cPtr == 0) ? null : new RSET(cPtr, true);
  }

  public long GetTotalEntries() {
    return IBJNI.IRSET_GetTotalEntries(swigCPtr, this);
  }

  public long GetHitTotal() {
    return IBJNI.IRSET_GetHitTotal(swigCPtr, this);
  }

  public IRSET Or(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_Or(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Nor(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_Nor(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET And(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_And(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Nand(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_Nand(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET AndNot(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_AndNot(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Xor(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_Xor(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Near(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_Near(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Far(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_Far(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET After(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_After(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Before(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_Before(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Adj(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_Adj(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Follows(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_Follows(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Precedes(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_Precedes(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Neighbor(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_Neighbor(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Peer(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_Peer(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET BeforePeer(IRSET Irset) {
    long cPtr = IBJNI.IRSET_BeforePeer(swigCPtr, this, IRSET.getCPtr(Irset), Irset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET AfterPeer(IRSET Irset) {
    long cPtr = IBJNI.IRSET_AfterPeer(swigCPtr, this, IRSET.getCPtr(Irset), Irset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET XPeer(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_XPeer(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Within(String FieldName) {
    long cPtr = IBJNI.IRSET_Within__SWIG_0(swigCPtr, this, FieldName);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Within(IRSET OtherIrset, String FieldName) {
    long cPtr = IBJNI.IRSET_Within__SWIG_1(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset, FieldName);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET BeforeWithin(IRSET OtherIrset, String FieldName) {
    long cPtr = IBJNI.IRSET_BeforeWithin(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset, FieldName);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET AfterWithin(IRSET OtherIrset, String FieldName) {
    long cPtr = IBJNI.IRSET_AfterWithin(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset, FieldName);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET XWithin(String FieldName) {
    long cPtr = IBJNI.IRSET_XWithin(swigCPtr, this, FieldName);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Inside(String FieldName) {
    long cPtr = IBJNI.IRSET_Inside(swigCPtr, this, FieldName);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET WithinXChars(IRSET OtherIrset, float Metric) {
    long cPtr = IBJNI.IRSET_WithinXChars__SWIG_0(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset, Metric);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET WithinXChars(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_WithinXChars__SWIG_1(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET WithinXChars_Before(IRSET OtherIrset, float Metric) {
    long cPtr = IBJNI.IRSET_WithinXChars_Before__SWIG_0(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset, Metric);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET WithinXChars_Before(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_WithinXChars_Before__SWIG_1(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET WithinXChars_After(IRSET OtherIrset, float Metric) {
    long cPtr = IBJNI.IRSET_WithinXChars_After__SWIG_0(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset, Metric);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET WithinXChars_After(IRSET OtherIrset) {
    long cPtr = IBJNI.IRSET_WithinXChars_After__SWIG_1(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET WithinXPercent(IRSET OtherIrset, float Percent) {
    long cPtr = IBJNI.IRSET_WithinXPercent(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset, Percent);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET WithinXPercent_Before(IRSET OtherIrset, float Percent) {
    long cPtr = IBJNI.IRSET_WithinXPercent_Before(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset, Percent);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET WithinXPercent_After(IRSET OtherIrset, float Percent) {
    long cPtr = IBJNI.IRSET_WithinXPercent_After(swigCPtr, this, IRSET.getCPtr(OtherIrset), OtherIrset, Percent);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Not() {
    long cPtr = IBJNI.IRSET_Not(swigCPtr, this);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Reduce(int Value) {
    long cPtr = IBJNI.IRSET_Reduce__SWIG_0(swigCPtr, this, Value);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public IRSET Reduce() {
    long cPtr = IBJNI.IRSET_Reduce__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new IRSET(cPtr, false);
  }

  public void ComputeScores(int TermWeight) {
    IBJNI.IRSET_ComputeScores(swigCPtr, this, TermWeight);
  }

  public void SortBy(SortBy SortBy) {
    IBJNI.IRSET_SortBy(swigCPtr, this, SortBy.swigValue());
  }

  public double GetMaxScore() {
    return IBJNI.IRSET_GetMaxScore(swigCPtr, this);
  }

  public double GetMinScore() {
    return IBJNI.IRSET_GetMinScore(swigCPtr, this);
  }

}
