/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class LANGUAGE {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LANGUAGE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LANGUAGE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_LANGUAGE(swigCPtr);
    }
    swigCPtr = 0;
  }

  public LANGUAGE(String Name) {
    this(IBJNI.new_LANGUAGE(Name), true);
  }

  public String Name() {
    return IBJNI.LANGUAGE_Name(swigCPtr, this);
  }

  public String Code() {
    return IBJNI.LANGUAGE_Code(swigCPtr, this);
  }

}
