/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class LOCALE {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LOCALE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LOCALE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_LOCALE(swigCPtr);
    }
    swigCPtr = 0;
  }

  public LOCALE() {
    this(IBJNI.new_LOCALE(), true);
  }

  public LOCALE SetLanguage(LANGUAGE Other) {
    return new LOCALE(IBJNI.LOCALE_SetLanguage(swigCPtr, this, LANGUAGE.getCPtr(Other), Other), true);
  }

  public LOCALE SetCharset(CHARSET Other) {
    return new LOCALE(IBJNI.LOCALE_SetCharset(swigCPtr, this, CHARSET.getCPtr(Other), Other), true);
  }

  public String GetLanguageCode() {
    return IBJNI.LOCALE_GetLanguageCode(swigCPtr, this);
  }

  public String GetLanguageName() {
    return IBJNI.LOCALE_GetLanguageName(swigCPtr, this);
  }

  public String GetCharsetCode() {
    return IBJNI.LOCALE_GetCharsetCode(swigCPtr, this);
  }

  public String GetCharsetName() {
    return IBJNI.LOCALE_GetCharsetName(swigCPtr, this);
  }

  public CHARSET Charset() {
    return new CHARSET(IBJNI.LOCALE_Charset(swigCPtr, this), true);
  }

  public LANGUAGE Language() {
    return new LANGUAGE(IBJNI.LOCALE_Language(swigCPtr, this), true);
  }

  public String Name() {
    return IBJNI.LOCALE_Name(swigCPtr, this);
  }

  public int Id() {
    return IBJNI.LOCALE_Id(swigCPtr, this);
  }

}
