/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class MDT {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MDT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MDT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_MDT(swigCPtr);
    }
    swigCPtr = 0;
  }

  public MDT(String DbFileStem, boolean WrongEndian) {
    this(IBJNI.new_MDT(DbFileStem, WrongEndian), true);
  }

  public String GetFileStem() {
    return IBJNI.MDT_GetFileStem(swigCPtr, this);
  }

  public void SetEntry(long Index, MDTREC MdtRecord) {
    IBJNI.MDT_SetEntry(swigCPtr, this, Index, MDTREC.getCPtr(MdtRecord), MdtRecord);
  }

  public long LookupByKey(String Key) {
    return IBJNI.MDT_LookupByKey(swigCPtr, this, Key);
  }

  public MDTREC GetEntry(long Index) {
    long cPtr = IBJNI.MDT_GetEntry(swigCPtr, this, Index);
    return (cPtr == 0) ? null : new MDTREC(cPtr, false);
  }

  public boolean Delete(long Index) {
    return IBJNI.MDT_Delete(swigCPtr, this, Index);
  }

  public boolean UnDelete(long Index) {
    return IBJNI.MDT_UnDelete(swigCPtr, this, Index);
  }

  public boolean IsDeleted(long Index) {
    return IBJNI.MDT_IsDeleted(swigCPtr, this, Index);
  }

  public long GetTotalEntries() {
    return IBJNI.MDT_GetTotalEntries(swigCPtr, this);
  }

  public long GetTotalDeleted() {
    return IBJNI.MDT_GetTotalDeleted(swigCPtr, this);
  }

  public boolean GetChanged() {
    return IBJNI.MDT_GetChanged(swigCPtr, this);
  }

  public long RemoveDeleted() {
    return IBJNI.MDT_RemoveDeleted(swigCPtr, this);
  }

  public boolean Ok() {
    return IBJNI.MDT_Ok(swigCPtr, this);
  }

}
