/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class MDTREC {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MDTREC(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MDTREC obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_MDTREC(swigCPtr);
    }
    swigCPtr = 0;
  }

  public MDTREC(MDT MdtPtr) {
    this(IBJNI.new_MDTREC__SWIG_0(MDT.getCPtr(MdtPtr), MdtPtr), true);
  }

  public MDTREC() {
    this(IBJNI.new_MDTREC__SWIG_1(), true);
  }

  public void SetCategory(long newCategory) {
    IBJNI.MDTREC_SetCategory(swigCPtr, this, newCategory);
  }

  public long GetCategory() {
    return IBJNI.MDTREC_GetCategory(swigCPtr, this);
  }

  public void SetPriority(short newPriority) {
    IBJNI.MDTREC_SetPriority(swigCPtr, this, newPriority);
  }

  public short GetPriority() {
    return IBJNI.MDTREC_GetPriority(swigCPtr, this);
  }

  public void SetKey(String NewKey) {
    IBJNI.MDTREC_SetKey(swigCPtr, this, NewKey);
  }

  public String GetKey() {
    return IBJNI.MDTREC_GetKey(swigCPtr, this);
  }

  public void SetDocumentType(DOCTYPE_ID NewDoctypeId) {
    IBJNI.MDTREC_SetDocumentType(swigCPtr, this, DOCTYPE_ID.getCPtr(NewDoctypeId), NewDoctypeId);
  }

  public DOCTYPE_ID GetDocumentType() {
    return new DOCTYPE_ID(IBJNI.MDTREC_GetDocumentType(swigCPtr, this), true);
  }

  public void SetPath(String NewPathName) {
    IBJNI.MDTREC_SetPath(swigCPtr, this, NewPathName);
  }

  public String GetPath() {
    return IBJNI.MDTREC_GetPath(swigCPtr, this);
  }

  public void SetFileName(String NewFileName) {
    IBJNI.MDTREC_SetFileName(swigCPtr, this, NewFileName);
  }

  public String GetFileName() {
    return IBJNI.MDTREC_GetFileName(swigCPtr, this);
  }

  public void SetFullFileName(String NewFullPath) {
    IBJNI.MDTREC_SetFullFileName(swigCPtr, this, NewFullPath);
  }

  public String GetFullFileName() {
    return IBJNI.MDTREC_GetFullFileName(swigCPtr, this);
  }

  public void SetGlobalFileStart(java.math.BigInteger NewStart) {
    IBJNI.MDTREC_SetGlobalFileStart(swigCPtr, this, NewStart);
  }

  public java.math.BigInteger GetGlobalFileStart() {
    return IBJNI.MDTREC_GetGlobalFileStart(swigCPtr, this);
  }

  public void SetLocalRecordStart(java.math.BigInteger NewStart) {
    IBJNI.MDTREC_SetLocalRecordStart(swigCPtr, this, NewStart);
  }

  public java.math.BigInteger GetLocalRecordStart() {
    return IBJNI.MDTREC_GetLocalRecordStart(swigCPtr, this);
  }

  public void SetLocalRecordEnd(java.math.BigInteger NewEnd) {
    IBJNI.MDTREC_SetLocalRecordEnd(swigCPtr, this, NewEnd);
  }

  public java.math.BigInteger GetLocalRecordEnd() {
    return IBJNI.MDTREC_GetLocalRecordEnd(swigCPtr, this);
  }

  public void SetLocale(LOCALE NewLocale) {
    IBJNI.MDTREC_SetLocale(swigCPtr, this, LOCALE.getCPtr(NewLocale), NewLocale);
  }

  public LOCALE GetLocale() {
    return new LOCALE(IBJNI.MDTREC_GetLocale(swigCPtr, this), true);
  }

  public void SetDate(SRCH_DATE NewDate) {
    IBJNI.MDTREC_SetDate(swigCPtr, this, SRCH_DATE.getCPtr(NewDate), NewDate);
  }

  public SRCH_DATE GetDate() {
    return new SRCH_DATE(IBJNI.MDTREC_GetDate(swigCPtr, this), true);
  }

  public void SetDateModified(SRCH_DATE NewDate) {
    IBJNI.MDTREC_SetDateModified(swigCPtr, this, SRCH_DATE.getCPtr(NewDate), NewDate);
  }

  public SRCH_DATE GetDateModified() {
    return new SRCH_DATE(IBJNI.MDTREC_GetDateModified(swigCPtr, this), true);
  }

  public void SetDateCreated(SRCH_DATE NewDate) {
    IBJNI.MDTREC_SetDateCreated(swigCPtr, this, SRCH_DATE.getCPtr(NewDate), NewDate);
  }

  public SRCH_DATE GetDateCreated() {
    return new SRCH_DATE(IBJNI.MDTREC_GetDateCreated(swigCPtr, this), true);
  }

  public void SetDateExpires(SRCH_DATE NewDate) {
    IBJNI.MDTREC_SetDateExpires(swigCPtr, this, SRCH_DATE.getCPtr(NewDate), NewDate);
  }

  public SRCH_DATE GetDateExpires() {
    return new SRCH_DATE(IBJNI.MDTREC_GetDateExpires(swigCPtr, this), true);
  }

  public int TTL() {
    return IBJNI.MDTREC_TTL__SWIG_0(swigCPtr, this);
  }

  public int TTL(SRCH_DATE Now) {
    return IBJNI.MDTREC_TTL__SWIG_1(swigCPtr, this, SRCH_DATE.getCPtr(Now), Now);
  }

  public void SetDeleted(boolean Flag) {
    IBJNI.MDTREC_SetDeleted(swigCPtr, this, Flag);
  }

  public boolean GetDeleted() {
    return IBJNI.MDTREC_GetDeleted(swigCPtr, this);
  }

  public void FlipBytes() {
    IBJNI.MDTREC_FlipBytes(swigCPtr, this);
  }

  public String Dump() {
    return IBJNI.MDTREC_Dump(swigCPtr, this);
  }

}
