/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class NODETREE {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NODETREE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NODETREE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_NODETREE(swigCPtr);
    }
    swigCPtr = 0;
  }

  public NODETREE() {
    this(IBJNI.new_NODETREE__SWIG_0(), true);
  }

  public NODETREE(NODETREE table) {
    this(IBJNI.new_NODETREE__SWIG_1(NODETREE.getCPtr(table), table), true);
  }

  public SWIGTYPE_p_TREENODELIST AddEntry(TREENODE Node) {
    long cPtr = IBJNI.NODETREE_AddEntry__SWIG_0(swigCPtr, this, TREENODE.getCPtr(Node), Node);
    return (cPtr == 0) ? null : new SWIGTYPE_p_TREENODELIST(cPtr, false);
  }

  public SWIGTYPE_p_TREENODELIST AddEntry(NODETREE table) {
    long cPtr = IBJNI.NODETREE_AddEntry__SWIG_1(swigCPtr, this, NODETREE.getCPtr(table), table);
    return (cPtr == 0) ? null : new SWIGTYPE_p_TREENODELIST(cPtr, false);
  }

  public void Clear() {
    IBJNI.NODETREE_Clear(swigCPtr, this);
  }

  public void Reverse() {
    IBJNI.NODETREE_Reverse(swigCPtr, this);
  }

  public void Sort() {
    IBJNI.NODETREE_Sort(swigCPtr, this);
  }

  public boolean IsSorted() {
    return IBJNI.NODETREE_IsSorted(swigCPtr, this);
  }

  public boolean IsEmpty() {
    return IBJNI.NODETREE_IsEmpty(swigCPtr, this);
  }

  public TREENODE GetEntry(int Index) {
    return new TREENODE(IBJNI.NODETREE_GetEntry(swigCPtr, this, Index), true);
  }

  public String XMLNodeTree(String value) {
    return IBJNI.NODETREE_XMLNodeTree__SWIG_0(swigCPtr, this, value);
  }

  public String XMLNodeTree() {
    return IBJNI.NODETREE_XMLNodeTree__SWIG_1(swigCPtr, this);
  }

}
