/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class NormalizationMethods {
  public final static NormalizationMethods Unnormalized = new NormalizationMethods("Unnormalized", IBJNI.Unnormalized_get());
  public final static NormalizationMethods NoNormalization = new NormalizationMethods("NoNormalization");
  public final static NormalizationMethods CosineNormalization = new NormalizationMethods("CosineNormalization");
  public final static NormalizationMethods MaxNormalization = new NormalizationMethods("MaxNormalization");
  public final static NormalizationMethods LogNormalization = new NormalizationMethods("LogNormalization");
  public final static NormalizationMethods BytesNormalization = new NormalizationMethods("BytesNormalization");
  public final static NormalizationMethods preCosineMetricNormalization = new NormalizationMethods("preCosineMetricNormalization");
  public final static NormalizationMethods CosineMetricNormalization = new NormalizationMethods("CosineMetricNormalization");
  public final static NormalizationMethods UndefinedNormalization = new NormalizationMethods("UndefinedNormalization");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NormalizationMethods swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NormalizationMethods.class + " with value " + swigValue);
  }

  private NormalizationMethods(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NormalizationMethods(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NormalizationMethods(String swigName, NormalizationMethods swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NormalizationMethods[] swigValues = { Unnormalized, NoNormalization, CosineNormalization, MaxNormalization, LogNormalization, BytesNormalization, preCosineMetricNormalization, CosineMetricNormalization, UndefinedNormalization };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

