/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class OPERATOR {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OPERATOR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OPERATOR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_OPERATOR(swigCPtr);
    }
    swigCPtr = 0;
  }

  public OPERATOR() {
    this(IBJNI.new_OPERATOR(), true);
  }

  public SWIGTYPE_p_t_OpType GetOpType() {
    return new SWIGTYPE_p_t_OpType(IBJNI.OPERATOR_GetOpType(swigCPtr, this), true);
  }

  public void SetOperatorType(t_Operator OperatorType) {
    IBJNI.OPERATOR_SetOperatorType(swigCPtr, this, OperatorType.swigValue());
  }

  public t_Operator GetOperatorType() {
    return t_Operator.swigToEnum(IBJNI.OPERATOR_GetOperatorType(swigCPtr, this));
  }

  public void SetOperatorMetric(float Metric) {
    IBJNI.OPERATOR_SetOperatorMetric(swigCPtr, this, Metric);
  }

  public float GetOperatorMetric() {
    return IBJNI.OPERATOR_GetOperatorMetric(swigCPtr, this);
  }

  public void SetOperatorString(String Arg) {
    IBJNI.OPERATOR_SetOperatorString(swigCPtr, this, Arg);
  }

  public String GetOperatorString() {
    return IBJNI.OPERATOR_GetOperatorString(swigCPtr, this);
  }

}
