/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class QUERY {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected QUERY(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QUERY obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_QUERY(swigCPtr);
    }
    swigCPtr = 0;
  }

  public QUERY() {
    this(IBJNI.new_QUERY(), true);
  }

  public void SetSQUERY(SQUERY newQuery) {
    IBJNI.QUERY_SetSQUERY(swigCPtr, this, SQUERY.getCPtr(newQuery), newQuery);
  }

  public SQUERY GetSQUERY() {
    return new SQUERY(IBJNI.QUERY_GetSQUERY(swigCPtr, this), false);
  }

  public void SetNormalizationMethod(NormalizationMethods newMethod) {
    IBJNI.QUERY_SetNormalizationMethod(swigCPtr, this, newMethod.swigValue());
  }

  public NormalizationMethods GetNormalizationMethod() {
    return NormalizationMethods.swigToEnum(IBJNI.QUERY_GetNormalizationMethod(swigCPtr, this));
  }

  public void SetSortBy(SortBy newSort) {
    IBJNI.QUERY_SetSortBy(swigCPtr, this, newSort.swigValue());
  }

  public SortBy GetSortBy() {
    return SortBy.swigToEnum(IBJNI.QUERY_GetSortBy(swigCPtr, this));
  }

  public long GetMaximumResults() {
    return IBJNI.QUERY_GetMaximumResults(swigCPtr, this);
  }

  public void SetMaximumResults(long newMax) {
    IBJNI.QUERY_SetMaximumResults(swigCPtr, this, newMax);
  }

}
