/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class QueryTypeMethods {
  public final static QueryTypeMethods QueryAutodetect = new QueryTypeMethods("QueryAutodetect", IBJNI.QueryAutodetect_get());
  public final static QueryTypeMethods QueryRPN = new QueryTypeMethods("QueryRPN");
  public final static QueryTypeMethods QueryInfix = new QueryTypeMethods("QueryInfix");
  public final static QueryTypeMethods QueryRelevantId = new QueryTypeMethods("QueryRelevantId");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static QueryTypeMethods swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + QueryTypeMethods.class + " with value " + swigValue);
  }

  private QueryTypeMethods(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private QueryTypeMethods(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private QueryTypeMethods(String swigName, QueryTypeMethods swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static QueryTypeMethods[] swigValues = { QueryAutodetect, QueryRPN, QueryInfix, QueryRelevantId };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

