/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SCANOBJ {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SCANOBJ(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SCANOBJ obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_SCANOBJ(swigCPtr);
    }
    swigCPtr = 0;
  }

  public SCANOBJ(String Term, long Freq) {
    this(IBJNI.new_SCANOBJ(Term, Freq), true);
  }

  public long Frequency() {
    return IBJNI.SCANOBJ_Frequency(swigCPtr, this);
  }

  public String Term() {
    return IBJNI.SCANOBJ_Term(swigCPtr, this);
  }

}
