/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class SortBy {
  public final static SortBy Unsorted = new SortBy("Unsorted");
  public final static SortBy ByDate = new SortBy("ByDate");
  public final static SortBy ByReverseDate = new SortBy("ByReverseDate");
  public final static SortBy ByScore = new SortBy("ByScore");
  public final static SortBy ByAdjScore = new SortBy("ByAdjScore");
  public final static SortBy ByAuxCount = new SortBy("ByAuxCount");
  public final static SortBy ByHits = new SortBy("ByHits");
  public final static SortBy ByReverseHits = new SortBy("ByReverseHits");
  public final static SortBy ByKey = new SortBy("ByKey");
  public final static SortBy ByIndex = new SortBy("ByIndex");
  public final static SortBy ByCategory = new SortBy("ByCategory");
  public final static SortBy ByNewsrank = new SortBy("ByNewsrank");
  public final static SortBy ByFunction = new SortBy("ByFunction");
  public final static SortBy ByPrivate = new SortBy("ByPrivate");
  public final static SortBy ByPrivateLocal1 = new SortBy("ByPrivateLocal1");
  public final static SortBy ByPrivateLocal2 = new SortBy("ByPrivateLocal2");
  public final static SortBy ByPrivateLocal3 = new SortBy("ByPrivateLocal3");
  public final static SortBy ByExtIndex = new SortBy("ByExtIndex", IBJNI.ByExtIndex_get());
  public final static SortBy ByExtIndex1 = new SortBy("ByExtIndex1");
  public final static SortBy ByExtIndex2 = new SortBy("ByExtIndex2");
  public final static SortBy ByExtIndex3 = new SortBy("ByExtIndex3");
  public final static SortBy ByExtIndex4 = new SortBy("ByExtIndex4");
  public final static SortBy ByExtIndex5 = new SortBy("ByExtIndex5");
  public final static SortBy ByExtIndex6 = new SortBy("ByExtIndex6");
  public final static SortBy ByExtIndex7 = new SortBy("ByExtIndex7");
  public final static SortBy ByExtIndex8 = new SortBy("ByExtIndex8");
  public final static SortBy ByExtIndex9 = new SortBy("ByExtIndex9");
  public final static SortBy ByExtIndex10 = new SortBy("ByExtIndex10");
  public final static SortBy ByExtIndex11 = new SortBy("ByExtIndex11");
  public final static SortBy ByExtIndex12 = new SortBy("ByExtIndex12");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SortBy swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SortBy.class + " with value " + swigValue);
  }

  private SortBy(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SortBy(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SortBy(String swigName, SortBy swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SortBy[] swigValues = { Unsorted, ByDate, ByReverseDate, ByScore, ByAdjScore, ByAuxCount, ByHits, ByReverseHits, ByKey, ByIndex, ByCategory, ByNewsrank, ByFunction, ByPrivate, ByPrivateLocal1, ByPrivateLocal2, ByPrivateLocal3, ByExtIndex, ByExtIndex1, ByExtIndex2, ByExtIndex3, ByExtIndex4, ByExtIndex5, ByExtIndex6, ByExtIndex7, ByExtIndex8, ByExtIndex9, ByExtIndex10, ByExtIndex11, ByExtIndex12 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

