/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SQUERY {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SQUERY(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SQUERY obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_SQUERY(swigCPtr);
    }
    swigCPtr = 0;
  }

  public SQUERY() {
    this(IBJNI.new_SQUERY__SWIG_0(), true);
  }

  public SQUERY(SQUERY OtherSquery) {
    this(IBJNI.new_SQUERY__SWIG_1(SQUERY.getCPtr(OtherSquery), OtherSquery), true);
  }

  public SQUERY(String Sentence, QueryTypeMethods Typ, THESAURUS Ptr) {
    this(IBJNI.new_SQUERY__SWIG_2(Sentence, Typ.swigValue(), THESAURUS.getCPtr(Ptr), Ptr), true);
  }

  public SQUERY(String Sentence, QueryTypeMethods Typ) {
    this(IBJNI.new_SQUERY__SWIG_3(Sentence, Typ.swigValue()), true);
  }

  public SQUERY(String Sentence) {
    this(IBJNI.new_SQUERY__SWIG_4(Sentence), true);
  }

  public long GetTotalTerms() {
    return IBJNI.SQUERY_GetTotalTerms(swigCPtr, this);
  }

  public boolean SetOperator(OPERATOR Operator) {
    return IBJNI.SQUERY_SetOperator(swigCPtr, this, OPERATOR.getCPtr(Operator), Operator);
  }

  public boolean SetOperatorAndWithin(String FieldName) {
    return IBJNI.SQUERY_SetOperatorAndWithin(swigCPtr, this, FieldName);
  }

  public boolean SetOperatorNear() {
    return IBJNI.SQUERY_SetOperatorNear(swigCPtr, this);
  }

  public boolean SetOperatorPeer() {
    return IBJNI.SQUERY_SetOperatorPeer(swigCPtr, this);
  }

  public long SetAttributes(SWIGTYPE_p_ATTRLIST Attrlist, boolean Replace) {
    return IBJNI.SQUERY_SetAttributes__SWIG_0(swigCPtr, this, SWIGTYPE_p_ATTRLIST.getCPtr(Attrlist), Replace);
  }

  public long SetAttributes(SWIGTYPE_p_ATTRLIST Attrlist) {
    return IBJNI.SQUERY_SetAttributes__SWIG_1(swigCPtr, this, SWIGTYPE_p_ATTRLIST.getCPtr(Attrlist));
  }

  public boolean isPlainQuery() {
    return IBJNI.SQUERY_isPlainQuery(swigCPtr, this);
  }

  public boolean isOpQuery(t_Operator Operator) {
    return IBJNI.SQUERY_isOpQuery(swigCPtr, this, Operator.swigValue());
  }

  public long SetRelevantTerm(String RelId) {
    return IBJNI.SQUERY_SetRelevantTerm(swigCPtr, this, RelId);
  }

  public long SetInfixTerm(String NewTerm) {
    return IBJNI.SQUERY_SetInfixTerm(swigCPtr, this, NewTerm);
  }

  public long SetRpnTerm(String NewTerm) {
    return IBJNI.SQUERY_SetRpnTerm(swigCPtr, this, NewTerm);
  }

  public long SetQueryTerm(String NewTerm) {
    return IBJNI.SQUERY_SetQueryTerm(swigCPtr, this, NewTerm);
  }

  public long SetQueryTermUTF(String UtfTerm) {
    return IBJNI.SQUERY_SetQueryTermUTF(swigCPtr, this, UtfTerm);
  }

  public long SetWords(String NewTerm, int Weight) {
    return IBJNI.SQUERY_SetWords__SWIG_0(swigCPtr, this, NewTerm, Weight);
  }

  public long SetWords(String NewTerm) {
    return IBJNI.SQUERY_SetWords__SWIG_1(swigCPtr, this, NewTerm);
  }

  public long SetWordsAnd(String NewTerm, int Weight) {
    return IBJNI.SQUERY_SetWordsAnd__SWIG_0(swigCPtr, this, NewTerm, Weight);
  }

  public long SetWordsAnd(String NewTerm) {
    return IBJNI.SQUERY_SetWordsAnd__SWIG_1(swigCPtr, this, NewTerm);
  }

  public long SetWords(String Words, OPERATOR BinaryOperator, int Weight) {
    return IBJNI.SQUERY_SetWords__SWIG_2(swigCPtr, this, Words, OPERATOR.getCPtr(BinaryOperator), BinaryOperator, Weight);
  }

  public long SetWords(String Words, OPERATOR BinaryOperator) {
    return IBJNI.SQUERY_SetWords__SWIG_3(swigCPtr, this, Words, OPERATOR.getCPtr(BinaryOperator), BinaryOperator);
  }

  public long SetFreeFormWords(String Sentence, int Weight) {
    return IBJNI.SQUERY_SetFreeFormWords__SWIG_0(swigCPtr, this, Sentence, Weight);
  }

  public long SetFreeFormWords(String Sentence) {
    return IBJNI.SQUERY_SetFreeFormWords__SWIG_1(swigCPtr, this, Sentence);
  }

  public long SetFreeFormWordsPhonetic(String Sentence, int Weight) {
    return IBJNI.SQUERY_SetFreeFormWordsPhonetic(swigCPtr, this, Sentence, Weight);
  }

  public String LastErrorMessage() {
    return IBJNI.SQUERY_LastErrorMessage(swigCPtr, this);
  }

  public String GetRpnTerm() {
    return IBJNI.SQUERY_GetRpnTerm(swigCPtr, this);
  }

  public SQUERY Cat(SQUERY OtherSquery) {
    return new SQUERY(IBJNI.SQUERY_Cat__SWIG_0(swigCPtr, this, SQUERY.getCPtr(OtherSquery), OtherSquery), false);
  }

  public SQUERY Cat(SQUERY OtherSquery, String Opname) {
    return new SQUERY(IBJNI.SQUERY_Cat__SWIG_1(swigCPtr, this, SQUERY.getCPtr(OtherSquery), OtherSquery, Opname), false);
  }

  public void OpenThesaurus(String FullPath) {
    IBJNI.SQUERY_OpenThesaurus(swigCPtr, this, FullPath);
  }

  public void CloseThesaurus() {
    IBJNI.SQUERY_CloseThesaurus(swigCPtr, this);
  }

  public void ExpandQuery() {
    IBJNI.SQUERY_ExpandQuery(swigCPtr, this);
  }

}
