/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SRCH_DATE {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SRCH_DATE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SRCH_DATE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_SRCH_DATE(swigCPtr);
    }
    swigCPtr = 0;
  }

  public SRCH_DATE(String Value) {
    this(IBJNI.new_SRCH_DATE__SWIG_0(Value), true);
  }

  public SRCH_DATE() {
    this(IBJNI.new_SRCH_DATE__SWIG_1(), true);
  }

  public SRCH_DATE(double FloatVal) {
    this(IBJNI.new_SRCH_DATE__SWIG_2(FloatVal), true);
  }

  public SRCH_DATE(int LongVal) {
    this(IBJNI.new_SRCH_DATE__SWIG_3(LongVal), true);
  }

  public SRCH_DATE Plus(SRCH_DATE OtherDate) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_Plus(swigCPtr, this, SRCH_DATE.getCPtr(OtherDate), OtherDate), true);
  }

  public SRCH_DATE Minus(SRCH_DATE OtherDate) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_Minus(swigCPtr, this, SRCH_DATE.getCPtr(OtherDate), OtherDate), true);
  }

  public SRCH_DATE PlusNseconds(int seconds) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_PlusNseconds(swigCPtr, this, seconds), true);
  }

  public SRCH_DATE PlusNminutes(int minutes) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_PlusNminutes(swigCPtr, this, minutes), true);
  }

  public SRCH_DATE PlusNhours(int hours) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_PlusNhours(swigCPtr, this, hours), true);
  }

  public SRCH_DATE PlusNdays(int days) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_PlusNdays(swigCPtr, this, days), true);
  }

  public SRCH_DATE PlusNweeks(int weeks) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_PlusNweeks(swigCPtr, this, weeks), true);
  }

  public SRCH_DATE PlusNmonths(int months) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_PlusNmonths(swigCPtr, this, months), true);
  }

  public SRCH_DATE PlusNyears(int years) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_PlusNyears(swigCPtr, this, years), true);
  }

  public SRCH_DATE MinusNseconds(int seconds) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_MinusNseconds(swigCPtr, this, seconds), true);
  }

  public SRCH_DATE MinusNminutes(int minutes) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_MinusNminutes(swigCPtr, this, minutes), true);
  }

  public SRCH_DATE MinusNhours(int hours) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_MinusNhours(swigCPtr, this, hours), true);
  }

  public SRCH_DATE MinusNdays(int days) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_MinusNdays(swigCPtr, this, days), true);
  }

  public SRCH_DATE MinusNweeks(int weeks) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_MinusNweeks(swigCPtr, this, weeks), true);
  }

  public SRCH_DATE MinusNmonths(int months) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_MinusNmonths(swigCPtr, this, months), true);
  }

  public SRCH_DATE MinusNyears(int years) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_MinusNyears(swigCPtr, this, years), true);
  }

  public SRCH_DATE Tommorrow() {
    return new SRCH_DATE(IBJNI.SRCH_DATE_Tommorrow(swigCPtr, this), true);
  }

  public SRCH_DATE Yesterday() {
    return new SRCH_DATE(IBJNI.SRCH_DATE_Yesterday(swigCPtr, this), true);
  }

  public SRCH_DATE NextWeek() {
    return new SRCH_DATE(IBJNI.SRCH_DATE_NextWeek(swigCPtr, this), true);
  }

  public SRCH_DATE LastWeek() {
    return new SRCH_DATE(IBJNI.SRCH_DATE_LastWeek(swigCPtr, this), true);
  }

  public SRCH_DATE NextMonth() {
    return new SRCH_DATE(IBJNI.SRCH_DATE_NextMonth(swigCPtr, this), true);
  }

  public SRCH_DATE LastMonth() {
    return new SRCH_DATE(IBJNI.SRCH_DATE_LastMonth(swigCPtr, this), true);
  }

  public SRCH_DATE NextYear() {
    return new SRCH_DATE(IBJNI.SRCH_DATE_NextYear(swigCPtr, this), true);
  }

  public SRCH_DATE LastYear() {
    return new SRCH_DATE(IBJNI.SRCH_DATE_LastYear(swigCPtr, this), true);
  }

  public double GetValue() {
    return IBJNI.SRCH_DATE_GetValue(swigCPtr, this);
  }

  public boolean IsYearDate() {
    return IBJNI.SRCH_DATE_IsYearDate(swigCPtr, this);
  }

  public boolean IsMonthDate() {
    return IBJNI.SRCH_DATE_IsMonthDate(swigCPtr, this);
  }

  public boolean IsDayDate() {
    return IBJNI.SRCH_DATE_IsDayDate(swigCPtr, this);
  }

  public boolean IsBogusDate() {
    return IBJNI.SRCH_DATE_IsBogusDate(swigCPtr, this);
  }

  public boolean IsValidDate() {
    return IBJNI.SRCH_DATE_IsValidDate(swigCPtr, this);
  }

  public boolean IsLeapYear() {
    return IBJNI.SRCH_DATE_IsLeapYear(swigCPtr, this);
  }

  public boolean Ok() {
    return IBJNI.SRCH_DATE_Ok(swigCPtr, this);
  }

  public boolean TrimToMonth() {
    return IBJNI.SRCH_DATE_TrimToMonth(swigCPtr, this);
  }

  public boolean TrimToYear() {
    return IBJNI.SRCH_DATE_TrimToYear(swigCPtr, this);
  }

  public boolean SetToYearStart() {
    return IBJNI.SRCH_DATE_SetToYearStart(swigCPtr, this);
  }

  public boolean SetToYearEnd() {
    return IBJNI.SRCH_DATE_SetToYearEnd(swigCPtr, this);
  }

  public boolean SetToMonthStart() {
    return IBJNI.SRCH_DATE_SetToMonthStart(swigCPtr, this);
  }

  public boolean SetToMonthEnd() {
    return IBJNI.SRCH_DATE_SetToMonthEnd(swigCPtr, this);
  }

  public boolean SetToDayStart() {
    return IBJNI.SRCH_DATE_SetToDayStart(swigCPtr, this);
  }

  public boolean SetToDayEnd() {
    return IBJNI.SRCH_DATE_SetToDayEnd(swigCPtr, this);
  }

  public boolean PromoteToMonthStart() {
    return IBJNI.SRCH_DATE_PromoteToMonthStart(swigCPtr, this);
  }

  public boolean PromoteToMonthEnd() {
    return IBJNI.SRCH_DATE_PromoteToMonthEnd(swigCPtr, this);
  }

  public boolean PromoteToDayStart() {
    return IBJNI.SRCH_DATE_PromoteToDayStart(swigCPtr, this);
  }

  public boolean PromoteToDayEnd() {
    return IBJNI.SRCH_DATE_PromoteToDayEnd(swigCPtr, this);
  }

  public void GetTodaysDate() {
    IBJNI.SRCH_DATE_GetTodaysDate(swigCPtr, this);
  }

  public void SetNow() {
    IBJNI.SRCH_DATE_SetNow(swigCPtr, this);
  }

  public boolean SetYear(int nYear) {
    return IBJNI.SRCH_DATE_SetYear(swigCPtr, this, nYear);
  }

  public boolean SetMonth(int nMonth) {
    return IBJNI.SRCH_DATE_SetMonth(swigCPtr, this, nMonth);
  }

  public boolean SetDay(int nDay) {
    return IBJNI.SRCH_DATE_SetDay(swigCPtr, this, nDay);
  }

  public int Year() {
    return IBJNI.SRCH_DATE_Year(swigCPtr, this);
  }

  public int Month() {
    return IBJNI.SRCH_DATE_Month(swigCPtr, this);
  }

  public int Day() {
    return IBJNI.SRCH_DATE_Day(swigCPtr, this);
  }

  public int DayOfWeek() {
    return IBJNI.SRCH_DATE_DayOfWeek(swigCPtr, this);
  }

  public int DayOfYear() {
    return IBJNI.SRCH_DATE_DayOfYear(swigCPtr, this);
  }

  public int GetFirstDayOfMonth() {
    return IBJNI.SRCH_DATE_GetFirstDayOfMonth(swigCPtr, this);
  }

  public int GetWeekOfMonth() {
    return IBJNI.SRCH_DATE_GetWeekOfMonth(swigCPtr, this);
  }

  public int WeekOfYear() {
    return IBJNI.SRCH_DATE_WeekOfYear(swigCPtr, this);
  }

  public int GetDaysInMonth() {
    return IBJNI.SRCH_DATE_GetDaysInMonth(swigCPtr, this);
  }

  public int GetJulianDate() {
    return IBJNI.SRCH_DATE_GetJulianDate(swigCPtr, this);
  }

  public int GetTimeSeconds() {
    return IBJNI.SRCH_DATE_GetTimeSeconds(swigCPtr, this);
  }

  public boolean SetTimeOfFile(String Pathname) {
    return IBJNI.SRCH_DATE_SetTimeOfFile(swigCPtr, this, Pathname);
  }

  public boolean SetTimeOfFileCreation(String Pathname) {
    return IBJNI.SRCH_DATE_SetTimeOfFileCreation(swigCPtr, this, Pathname);
  }

  public SRCH_DATE GetTimeOfFile(String Pathname) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_GetTimeOfFile(swigCPtr, this, Pathname), true);
  }

  public SRCH_DATE GetTimeOfFileCreation(String Pathname) {
    return new SRCH_DATE(IBJNI.SRCH_DATE_GetTimeOfFileCreation(swigCPtr, this, Pathname), true);
  }

  public boolean IsBefore(SRCH_DATE OtherDate) {
    return IBJNI.SRCH_DATE_IsBefore(swigCPtr, this, SRCH_DATE.getCPtr(OtherDate), OtherDate);
  }

  public boolean Equals(SRCH_DATE OtherDate) {
    return IBJNI.SRCH_DATE_Equals(swigCPtr, this, SRCH_DATE.getCPtr(OtherDate), OtherDate);
  }

  public boolean IsDuring(SRCH_DATE OtherDate) {
    return IBJNI.SRCH_DATE_IsDuring(swigCPtr, this, SRCH_DATE.getCPtr(OtherDate), OtherDate);
  }

  public boolean IsAfter(SRCH_DATE OtherDate) {
    return IBJNI.SRCH_DATE_IsAfter(swigCPtr, this, SRCH_DATE.getCPtr(OtherDate), OtherDate);
  }

  public String ISOdate() {
    return IBJNI.SRCH_DATE_ISOdate(swigCPtr, this);
  }

  public String RFCdate() {
    return IBJNI.SRCH_DATE_RFCdate(swigCPtr, this);
  }

  public String ANSIdate() {
    return IBJNI.SRCH_DATE_ANSIdate(swigCPtr, this);
  }

  public String LCdate() {
    return IBJNI.SRCH_DATE_LCdate(swigCPtr, this);
  }

  public String Strftime(String format) {
    return IBJNI.SRCH_DATE_Strftime(swigCPtr, this, format);
  }

}
