/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class STRLIST {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected STRLIST(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(STRLIST obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_STRLIST(swigCPtr);
    }
    swigCPtr = 0;
  }

  public STRLIST() {
    this(IBJNI.new_STRLIST__SWIG_0(), true);
  }

  public STRLIST(ArraySTRING Array) {
    this(IBJNI.new_STRLIST__SWIG_1(ArraySTRING.getCPtr(Array), Array), true);
  }

  public STRLIST(SWIGTYPE_p_p_char CStrList) {
    this(IBJNI.new_STRLIST__SWIG_2(SWIGTYPE_p_p_char.getCPtr(CStrList)), true);
  }

  public STRLIST Cat(STRLIST OtherVlist) {
    return new STRLIST(IBJNI.STRLIST_Cat__SWIG_0(swigCPtr, this, STRLIST.getCPtr(OtherVlist), OtherVlist), false);
  }

  public STRLIST Cat(ArraySTRING Array) {
    return new STRLIST(IBJNI.STRLIST_Cat__SWIG_1(swigCPtr, this, ArraySTRING.getCPtr(Array), Array), false);
  }

  public STRLIST Cat(SWIGTYPE_p_p_char CStrList) {
    return new STRLIST(IBJNI.STRLIST_Cat__SWIG_2(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(CStrList)), false);
  }

  public STRLIST AddEntry(String StringEntry) {
    long cPtr = IBJNI.STRLIST_AddEntry__SWIG_0(swigCPtr, this, StringEntry);
    return (cPtr == 0) ? null : new STRLIST(cPtr, false);
  }

  public STRLIST AddEntry(STRLIST Strlist) {
    long cPtr = IBJNI.STRLIST_AddEntry__SWIG_1(swigCPtr, this, STRLIST.getCPtr(Strlist), Strlist);
    return (cPtr == 0) ? null : new STRLIST(cPtr, false);
  }

  public STRLIST SetEntry(long Index, String StringEntry) {
    long cPtr = IBJNI.STRLIST_SetEntry(swigCPtr, this, Index, StringEntry);
    return (cPtr == 0) ? null : new STRLIST(cPtr, false);
  }

  public String GetEntry(long Index) {
    return IBJNI.STRLIST_GetEntry(swigCPtr, this, Index);
  }

  public boolean DeleteEntry(long pos) {
    return IBJNI.STRLIST_DeleteEntry(swigCPtr, this, pos);
  }

  public STRLIST Next() {
    long cPtr = IBJNI.STRLIST_Next(swigCPtr, this);
    return (cPtr == 0) ? null : new STRLIST(cPtr, false);
  }

  public STRLIST Prev() {
    long cPtr = IBJNI.STRLIST_Prev(swigCPtr, this);
    return (cPtr == 0) ? null : new STRLIST(cPtr, false);
  }

  public String Value() {
    return IBJNI.STRLIST_Value(swigCPtr, this);
  }

  public long GetTotalEntries() {
    return IBJNI.STRLIST_GetTotalEntries(swigCPtr, this);
  }

  public long Sort() {
    return IBJNI.STRLIST_Sort(swigCPtr, this);
  }

  public long UniqueSort() {
    return IBJNI.STRLIST_UniqueSort(swigCPtr, this);
  }

  public STRLIST SplitWords(String TheString) {
    return new STRLIST(IBJNI.STRLIST_SplitWords__SWIG_0(swigCPtr, this, TheString), false);
  }

  public STRLIST SplitTerms(String TheString) {
    return new STRLIST(IBJNI.STRLIST_SplitTerms__SWIG_0(swigCPtr, this, TheString), false);
  }

  public STRLIST SplitPaths(String TheString) {
    return new STRLIST(IBJNI.STRLIST_SplitPaths__SWIG_0(swigCPtr, this, TheString), false);
  }

  public STRLIST Split(char Separator, String TheString) {
    return new STRLIST(IBJNI.STRLIST_Split__SWIG_0(swigCPtr, this, Separator, TheString), false);
  }

  public STRLIST Split(String Separator, String TheString) {
    return new STRLIST(IBJNI.STRLIST_Split__SWIG_1(swigCPtr, this, Separator, TheString), false);
  }

  public String Join(char Separator) {
    return IBJNI.STRLIST_Join__SWIG_0(swigCPtr, this, Separator);
  }

  public String Join(String Separator) {
    return IBJNI.STRLIST_Join__SWIG_1(swigCPtr, this, Separator);
  }

  public long Search(String SearchTerm) {
    return IBJNI.STRLIST_Search(swigCPtr, this, SearchTerm);
  }

  public long SearchCase(String SearchTerm) {
    return IBJNI.STRLIST_SearchCase(swigCPtr, this, SearchTerm);
  }

  public String GetValue(String Title) {
    return IBJNI.STRLIST_GetValue(swigCPtr, this, Title);
  }

}
