/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class THESAURUS {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected THESAURUS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(THESAURUS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_THESAURUS(swigCPtr);
    }
    swigCPtr = 0;
  }

  public THESAURUS() {
    this(IBJNI.new_THESAURUS__SWIG_0(), true);
  }

  public THESAURUS(String Path) {
    this(IBJNI.new_THESAURUS__SWIG_1(Path), true);
  }

  public THESAURUS(String SourceFileName, String TargetPath, boolean Force) {
    this(IBJNI.new_THESAURUS__SWIG_2(SourceFileName, TargetPath, Force), true);
  }

  public boolean Compile(String Source, String Target, boolean Force) {
    return IBJNI.THESAURUS_Compile__SWIG_0(swigCPtr, this, Source, Target, Force);
  }

  public boolean Compile(String Source, String Target) {
    return IBJNI.THESAURUS_Compile__SWIG_1(swigCPtr, this, Source, Target);
  }

  public void SetFileName(String Fn) {
    IBJNI.THESAURUS_SetFileName(swigCPtr, this, Fn);
  }

}
