/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class TREENODE {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TREENODE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TREENODE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_TREENODE(swigCPtr);
    }
    swigCPtr = 0;
  }

  public TREENODE() {
    this(IBJNI.new_TREENODE__SWIG_0(), true);
  }

  public TREENODE(FC fc, String name) {
    this(IBJNI.new_TREENODE__SWIG_1(FC.getCPtr(fc), fc, name), true);
  }

  public String Name() {
    return IBJNI.TREENODE_Name(swigCPtr, this);
  }

  public FC Fc() {
    return new FC(IBJNI.TREENODE_Fc(swigCPtr, this), true);
  }

}
