/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class VIDB_STATS {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VIDB_STATS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VIDB_STATS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      IBJNI.delete_VIDB_STATS(swigCPtr);
    }
    swigCPtr = 0;
  }

  public VIDB_STATS() {
    this(IBJNI.new_VIDB_STATS(), true);
  }

  public void Clear() {
    IBJNI.VIDB_STATS_Clear(swigCPtr, this);
  }

  public void SetTotal(long i, long total) {
    IBJNI.VIDB_STATS_SetTotal(swigCPtr, this, i, total);
  }

  public void SetHits(long i, long total) {
    IBJNI.VIDB_STATS_SetHits(swigCPtr, this, i, total);
  }

  public void SetName(long i, String Name) {
    IBJNI.VIDB_STATS_SetName(swigCPtr, this, i, Name);
  }

}
