{"ab", "Abkhazian"},
{"abk", "Abkhazian"},
{"ace", "Achinese"},
{"ach", "Acoli"},
{"ada", "Adangme"},
{"om", "Afan Oromo"},
{"aa", "Afar"},
{"aar", "Afar"},
{"afr", "Africaans"},
{"afh", "Afrihili"},
{"af", "Afrikaans"},
{"afa", "Afro-Asiatic (Other)"},
{"aka", "Akan"},
{"akk", "Akkadian"},
{"alb", "Albanian"},
{"sqi", "Albanian"},
{"sq", "Albanian"},
{"ale", "Aleut"},
{"alg", "Algonquian languages"},
{"ajm", "Aljamia"},
{"tut", "Altaic (Other)"},
{"am", "Amharic"},
{"amh", "Amharic"},
{"apa", "Apache languages"},
{"ar", "Arabic"},
{"ara", "Arabic"},
{"arc", "Aramaic"},
{"arp", "Arapaho"},
{"arn", "Araucanian"},
{"arw", "Arawak"},
{"arm", "Armenian"},
{"hy", "Armenian"},
{"hye", "Armenian"},
{"art", "Artificial (Other)"},
{"as", "Assamese"},
{"asm", "Assamese"},
{"ath", "Athapascan languages"},
{"map", "Austronesian (Other)"},
{"ava", "Avaric"},
{"ave", "Avestan"},
{"awa", "Awandhi"},
{"ay", "Aymara"},
{"aym", "Aymara"},
{"az", "Azerbaijani"},
{"aze", "Azerbaijani"},
{"nah", "Aztec"},
{"ban", "Balinese"},
{"bat", "Baltic (Other)"},
{"bal", "Baluchi"},
{"bam", "Bambara"},
{"bai", "Bamileke languages"},
{"bad", "Banda"},
{"bas", "Basa"},
{"ba", "Bashkir"},
{"bak", "Bashkir"},
{"baq", "Basque"},
{"eu", "Basque"},
{"eus", "Basque"},
{"bej", "Beja"},
{"bem", "Bemba"},
{"ben", "Bengali"},
{"bn", "Bengali; Bangla"},
{"ber", "Berber languages"},
{"bho", "Bhojpuri"},
{"dz", "Bhutani"},
{"bh", "Bihari"},
{"bih", "Bihari"},
{"bik", "Bikol"},
{"bin", "Bini"},
{"bi", "Bislama"},
{"bis", "Bislama"},
{"bra", "Braj"},
{"br", "Breton"},
{"bre", "Breton"},
{"bug", "Buginese"},
{"bg", "Bulgarian"},
{"bul", "Bulgarian"},
{"bur", "Burmese"},
{"my", "Burmese"},
{"mya", "Burmese"},
{"be", "Byelorussian"},
{"bel", "Byelorussian"},
{"cad", "Caddo"},
{"km", "Cambodian"},
{"car", "Carib"},
{"ca", "Catalan"},
{"cat", "Catalan"},
{"cau", "Caucasian (Other)"},
{"ceb", "Cebuano"},
{"cel", "Celtic (Other)"},
{"cai", "Central American Indian (Other)"},
{"chg", "Chagatai"},
{"cha", "Chamorro"},
{"che", "Chechen"},
{"chr", "Cherokee"},
{"chy", "Cheyenne"},
{"chb", "Chibcha"},
{"chi", "Chinese"},
{"zh", "Chinese"},
{"zho", "Chinese"},
{"chn", "Chinook jargon"},
{"cho", "Choctaw"},
{"chu", "Church Slavic"},
{"chv", "Chuvash"},
{"cop", "Coptic"},
{"cor", "Cornish"},
{"co", "Corsican"},
{"cos", "Corsican"},
{"cre", "Cree"},
{"mus", "Creek"},
{"crp", "Creoles and pidgins (Other)"},
{"cpe", "Creoles and pidgins, English-based (Other)"},
{"cpf", "Creoles and pidgins, French-based (Other)"},
{"cpp", "Creoles and pidgins, Portuguese-based (Other)"},
{"hr", "Croatian"},
{"cus", "Cushitic (Other)"},
{"cs", "Czech"},
{"cze", "Czech"},
{"ces", "Czeck"},
{"dak", "Dakota"},
{"da", "Danish"},
{"dan", "Danish"},
{"del", "Delaware"},
{"din", "Dinka"},
{"doi", "Dogri"},
{"dra", "Dravidian (Other)"},
{"dua", "Duala"},
{"dut", "Dutch"},
{"nl", "Dutch"},
{"nld", "Dutch"},
{"dum", "Dutch, Middle (ca. 1050-1350)"},
{"dyu", "Dyula"},
{"dzo", "Dzongkha"},
{"efi", "Efik"},
{"egy", "Egyptian (Ancient)"},
{"eka", "Ekajuk"},
{"elx", "Elamite"},
{"en", "English"},
{"eng", "English"},
{"enm", "English, Middle (1100-1500)"},
{"ang", "English, Old (ca. 450-1100)"},
{"esk", "Eskimo (Other)"},
{"eo", "Esperanto"},
{"epo", "Esperanto"},
{"est", "Estonian"},
{"et", "Estonian"},
{"eth", "Ethiopic"},
{"ewe", "Ewe"},
{"ewo", "Ewondo"},
{"fo", "Faeroese"},
{"fan", "Fang"},
{"fat", "Fanti"},
{"fao", "Faroese"},
{"fj", "Fiji"},
{"fij", "Fijian"},
{"fi", "Finnish"},
{"fin", "Finnish"},
{"fiu", "Finno-Ugrian (Other)"},
{"fon", "Fon"},
{"fr", "French"},
{"fra", "French"},
{"fre", "French"},
{"frm", "French, Middel (ca. 1400-1600)"},
{"fro", "French, Old (ca. 842-1400)"},
{"fry", "Friesian"},
{"fy", "Frisian"},
{"ful", "Fulah"},
{"gaa", "Ga"},
{"gae", "Gaelic (Scots)"},
{"gdh", "Gaelic (Scots)"},
{"gl", "Galician"},
{"glg", "Gallegan"},
{"lug", "Ganda"},
{"gay", "Gayo"},
{"geo", "Georgian"},
{"ka", "Georgian"},
{"kat", "Georgian"},
{"de", "German"},
{"deu", "German"},
{"ger", "German"},
{"gmh", "German, Middle High (ca. 1050-1500)"},
{"goh", "German, Old High (ca. 750-1050)"},
{"gem", "Germanic (Other)"},
{"gil", "Gilbertese"},
{"gon", "Gondi"},
{"got", "Gothic"},
{"kl", "Greaenlandic"},
{"grb", "Grebo"},
{"el", "Greek"},
{"grc", "Greek, Ancient (to 1453)"},
{"ell", "Greek, Modern (1453- )"},
{"gre", "Greek, Modern (1453- )"},
{"kal", "Greenlandic"},
{"gn", "Guamni"},
{"grn", "Guarani"},
{"gu", "Gujarati"},
{"guj", "Gujarati"},
{"hai", "Haida"},
{"ha", "Hausa"},
{"hau", "Hausa"},
{"haw", "Hawaiian"},
{"he", "Hebrew"},
{"heb", "Hebrew"},
{"iw", "Hebrew, to be removed, see he"},
{"her", "Herero"},
{"hil", "Hiligaynon"},
{"him", "Himachali"},
{"hi", "Hindi"},
{"hin", "Hindi"},
{"hmo", "Hiri Motu"},
{"hu", "Hungarian"},
{"hun", "Hungarian"},
{"hup", "Hupa"},
{"iba", "Iban"},
{"ice", "Icelandic"},
{"is", "Icelandic"},
{"isl", "Icelandic"},
{"ibo", "Igbo"},
{"ijo", "Ijo"},
{"ilo", "Iloko"},
{"inc", "Indic (Other)"},
{"ine", "Indo-European (Other)"},
{"id", "Indonesian"},
{"ind", "Indonesian"},
{"in", "Indonesian, to be removed, see id"},
{"ia", "Interlingua"},
{"ina", "Interlingua (International Auxilary Language Association)"},
{"ile", "Interlingue"},
{"iku", "Inuktitut"},
{"iu", "Inuktitut (Eskimo)"},
{"ipk", "Inupiak"},
{"ira", "Iranian (Other)"},
{"ga", "Irish"},
{"gai", "Irish"},
{"iri", "Irish"},
{"iro", "Iroquoian languages"},
{"it", "Italian"},
{"ita", "Italian"},
{"ja", "Japanese"},
{"jpn", "Japanese"},
{"jav", "Javanese"},
{"jaw", "Javanese"},
{"jw", "Javanese"},
{"jrb", "Judeo-Arabic"},
{"jpr", "Judeo-Persian"},
{"kab", "Kabyle"},
{"kac", "Kachin"},
{"kam", "Kamba"},
{"kan", "Kannada"},
{"kn", "Kannada"},
{"kau", "Kanuri"},
{"kaa", "Kara-Kalpak"},
{"kar", "Karen"},
{"kas", "Kashmiri"},
{"ks", "Kashmiri"},
{"kaw", "Kawi"},
{"kaz", "Kazakh"},
{"kk", "Kazakh"},
{"kha", "Khasi"},
{"khm", "Khmer"},
{"khi", "Khoisan (Other)"},
{"kho", "Khotanese"},
{"kik", "Kikuyu"},
{"rw", "Kinya, Rwanda"},
{"kin", "Kinyarwanda"},
{"kir", "Kirghiz"},
{"ky", "Kirghiz"},
{"rn", "Kirundi"},
{"ik", "Knupiak"},
{"kon", "Kongo"},
{"kok", "Konkani"},
{"ko", "Korean"},
{"kor", "Korean"},
{"kpe", "Kpelle"},
{"kro", "Kru"},
{"kua", "Kuanyama"},
{"ku", "Kurdish"},
{"kur", "Kurdish"},
{"kru", "Kurukh"},
{"kus", "Kusaie"},
{"kut", "Kutenai"},
{"lad", "Ladino"},
{"lah", "Lahnda"},
{"lam", "Lamba"},
{"oci", "Langue d'oc (post 1500)"},
{"lao", "Lao"},
{"lo", "Laothian"},
{"lap", "Lapp languages"},
{"la", "Latin"},
{"lat", "Latin"},
{"lav", "Latvian"},
{"lv", "Latvian, Lettish"},
{"lin", "Lingala"},
{"ln", "Lingala"},
{"lt", "Lithuainnian"},
{"lit", "Lithuanian"},
{"ie", "lnteriingue"},
{"loz", "Lozi"},
{"lub", "Luba-Katanga"},
{"lui", "Luiseno"},
{"lun", "Lunda"},
{"luo", "Luo (Kenya and Tanzania)"},
{"mac", "Macedonian"},
{"mk", "Macedonian"},
{"mke", "Macedonian"},
{"mad", "Madurese"},
{"mag", "Magahi"},
{"mai", "Maithili"},
{"mak", "Makasar"},
{"mg", "Malagasy"},
{"mlg", "Malagasy"},
{"may", "Malay"},
{"ms", "Malay"},
{"msa", "Malay"},
{"mal", "Malayalam"},
{"ml", "Malayalam"},
{"mlt", "Maltese"},
{"mt", "Maltese"},
{"man", "Mandingo"},
{"mni", "Manipuri"},
{"mno", "Manobo languages"},
{"max", "Manx"},
{"mao", "Maori"},
{"mi", "Maori"},
{"mri", "Maori"},
{"mar", "Marathi"},
{"mr", "Marathi"},
{"mah", "Marshall"},
{"mwr", "Marwari"},
{"mas", "Masai"},
{"myn", "Mayan languages"},
{"men", "Mende"},
{"mic", "Micmac"},
{"min", "Minangkabau"},
{"mis", "Miscellaneous (Other)"},
{"moh", "Mohawk"},
{"mo", "Moldavian"},
{"mol", "Moldavian"},
{"mkh", "Mon-Khmer (Other)"},
{"lol", "Mongo"},
{"mn", "Mongolian"},
{"mon", "Mongolian"},
{"mos", "Mossi"},
{"mul", "Multiple languages"},
{"mun", "Munda (Other)"},
{"na", "Nauru"},
{"nau", "Nauru"},
{"nav", "Navajo"},
{"nde", "Ndebele (Zimbabwe)"},
{"ndo", "Ndonga"},
{"ne", "Nepali"},
{"nep", "Nepali"},
{"new", "Newari"},
{"nic", "Niger-Kordofanian (Other)"},
{"ssa", "Nilo-Saharan (Other)"},
{"niu", "Niuean"},
{"nai", "North American Indian (Other)"},
{"nso", "Northern Sohto"},
{"no", "Norwegian"},
{"nor", "Norwegian"},
{"nub", "Nubian languages"},
{"nym", "Nyamwezi"},
{"nya", "Nyanja"},
{"nyn", "Nyankole"},
{"nyo", "Nyoro"},
{"nzi", "Nzima"},
{"oc", "Occitan"},
{"oji", "Ojibwa"},
{"non", "Old Norse"},
{"peo", "Old Persian (ca. 600-400 B.C.)"},
{"or", "Oriya"},
{"ori", "Oriya"},
{"orm", "Oromo"},
{"osa", "Osage"},
{"oss", "Ossetic"},
{"oto", "Otomian languages"},
{"qu", "Ouechua"},
{"pal", "Pahlavi"},
{"pau", "Palauan"},
{"pli", "Pali"},
{"pam", "Pampanga"},
{"pag", "Pangasinan"},
{"pan", "Panjabi"},
{"pap", "Papiamento"},
{"paa", "Papuan-Australian (Other)"},
{"ps", "Pashto, Pushto"},
{"fa", "Persian"},
{"fas", "Persian"},
{"per", "Persian"},
{"pl", "Polish"},
{"pol", "Polish"},
{"pon", "Ponape"},
{"por", "Portuguese"},
{"pt", "Portuguese"},
{"pra", "Prakrit languages"},
{"pro", "Provencal, Old (to 1500)"},
{"pa", "Punjabi"},
{"pus", "Pushto"},
{"que", "Quechua"},
{"roh", "Raeto-Romance"},
{"raj", "Rajasthani"},
{"rar", "Rarotongan"},
{"rm", "Rhaeto-Romance"},
{"roa", "Romance (Other)"},
{"ro", "Romanian"},
{"ron", "Romanian"},
{"rum", "Romanian"},
{"rom", "Romany"},
{"run", "Rundi"},
{"ru", "Russian"},
{"rus", "Russian"},
{"sal", "Salishan languages"},
{"sam", "Samaritan Aramaic"},
{"sm", "Samoan"},
{"smo", "Samoan"},
{"sad", "Sandawe"},
{"sag", "Sango"},
{"sg", "Sangro"},
{"sa", "Sanskrit"},
{"san", "Sanskrit"},
{"sco", "Scots"},
{"gd", "Scots Gaelic"},
{"sel", "Selkup"},
{"sem", "Semitic (Other)"},
{"sr", "Serbian"},
{"scr", "Serbo-Croatian"},
{"sh", "Serbo-Croatian"},
{"srr", "Serer"},
{"st", "Sesotho"},
{"tn", "Setswana"},
{"shn", "Shan"},
{"sn", "Shona"},
{"sna", "Shona"},
{"sid", "Sidamo"},
{"bla", "Siksika"},
{"sd", "Sindhi"},
{"snd", "Sindhi"},
{"si", "Singhalese"},
{"sin", "Sinhalese"},
{"sit", "Sino-Tibetan (Other)"},
{"sio", "Siouan languages"},
{"ss", "Siswati"},
{"sla", "Slavic (Other)"},
{"sk", "Slovak"},
{"slk", "Slovak"},
{"slo", "Slovak"},
{"sl", "Slovenian"},
{"slv", "Slovenian"},
{"sog", "Sogdian"},
{"so", "Somali"},
{"som", "Somali"},
{"son", "Songhai"},
{"wen", "Sorbian languages"},
{"sot", "Sotho"},
{"sai", "South American Indian (Other)"},
{"es", "Spanish"},
{"esl", "Spanish"},
{"spa", "Spanish"},
{"suk", "Sukuma"},
{"sux", "Sumerian"},
{"su", "Sundanese"},
{"sun", "Sundanese"},
{"sus", "Susu"},
{"sw", "Swahili"},
{"swa", "Swahili"},
{"ssw", "Swazi"},
{"sv", "Swedish"},
{"sve", "Swedish"},
{"swe", "Swedish"},
{"syr", "Syriac"},
{"tgl", "Tagalog"},
{"tl", "Tagalog"},
{"tah", "Tahitian"},
{"tg", "Tajik"},
{"tgk", "Tajik"},
{"ta", "Tamil"},
{"tam", "Tamil"},
{"tat", "Tatar"},
{"tt", "Tatar"},
{"te", "Tegulu"},
{"tel", "Telugu"},
{"ter", "Tereno"},
{"th", "Thai"},
{"tha", "Thai"},
{"bo", "Tibetan"},
{"bod", "Tibetan"},
{"tib", "Tibetan"},
{"tig", "Tigre"},
{"ti", "Tigrinya"},
{"tir", "Tigrinya"},
{"tem", "Timne"},
{"tiv", "Tivi"},
{"tli", "Tlingit"},
{"to", "Tonga"},
{"tog", "Tonga (Nyasa)"},
{"ton", "Tonga (Tonga Islands)"},
{"tru", "Truk"},
{"tsi", "Tsimshian"},
{"ts", "Tsonga"},
{"tso", "Tsonga"},
{"tsn", "Tswana"},
{"tum", "Tumbuka"},
{"tr", "Turkish"},
{"tur", "Turkish"},
{"ota", "Turkish, Ottoman"},
{"tk", "Turkmen"},
{"tuk", "Turkmen"},
{"tw", "Twi"},
{"twi", "Twi"},
{"uga", "Ugaritic"},
{"uig", "Uighur"},
{"ug", "Uigur"},
{"uk", "Ukrainian"},
{"ukr", "Ukrainian"},
{"umb", "Umbundu"},
{"und", "Undetermined"},
{"ur", "Urdu"},
{"urd", "Urdu"},
{"uz", "Uzbek"},
{"uzb", "Uzbek"},
{"vai", "Vai"},
{"ven", "Venda"},
{"vi", "Vietnamese"},
{"vie", "Vietnamese"},
{"vol", "Volapuk"},
{"vo", "Volap&uuml;k"},
{"vot", "Votic"},
{"wak", "Wakashan languages"},
{"wal", "Walamo"},
{"war", "Waray"},
{"was", "Washo"},
{"cy", "Welsh"},
{"cym", "Welsh"},
{"we", "Welsh"},
{"wo", "Wolof"},
{"wo", "Wolof"},
{"wol", "Wolof"},
{"xh", "Xhosa"},
{"xh", "Xhosa"},
{"xho", "Xhosa"},
{"yao", "Yao"},
{"yap", "Yap"},
{"yi", "Yiddish"},
{"yid", "Yiddish"},
{"ji", "Yiddish"},
{"yo", "Yoruba"},
{"yo", "Yoruba"},
{"yor", "Yoruba"},
{"zap", "Zapotec"},
{"zen", "Zenaga"},
{"za", "Zhuang"},
{"zha", "Zhuang"},
{"zu", "Zulu"},
{"zul", "Zulu"},
{"zun", "Zuni"},
